// auto generated by c2z
const std = @import("std");
//const cpp = @import("cpp");

pub const DrawNavMeshFlags = extern struct {
    bits: c_int = 0,

    pub const DU_DRAWNAVMESH_OFFMESHCONS: DrawNavMeshFlags = .{ .bits = @as(c_uint, @intCast(1)) };
    pub const DU_DRAWNAVMESH_CLOSEDLIST: DrawNavMeshFlags = .{ .bits = @as(c_uint, @intCast(2)) };
    pub const DU_DRAWNAVMESH_COLOR_TILES: DrawNavMeshFlags = .{ .bits = @as(c_uint, @intCast(4)) };

    // pub usingnamespace cpp.FlagsMixin(DrawNavMeshFlags);
};

extern fn _1_duDebugDrawTileCacheContours_(dd: [*c]duDebugDraw, lcset: *const dtTileCacheContourSet, orig: [*c]const f32, cs: f32, ch: f32) void;
pub const duDebugDrawTileCacheContours = _1_duDebugDrawTileCacheContours_;

extern fn _1_duDebugDrawTileCachePolyMesh_(dd: [*c]duDebugDraw, lmesh: *const dtTileCachePolyMesh, orig: [*c]const f32, cs: f32, ch: f32) void;
pub const duDebugDrawTileCachePolyMesh = _1_duDebugDrawTileCachePolyMesh_;

// opaques

const duDebugDraw = anyopaque;
const dtTileCacheContourSet = anyopaque;
const dtTileCachePolyMesh = anyopaque;
