// auto generated by c2z
#include <new>
#include "DetourDebugDraw.h"

extern "C" void _1_duDebugDrawTileCacheContours_(duDebugDraw * dd, const struct dtTileCacheContourSet & lcset, const float * orig, const float cs, const float ch) { ::duDebugDrawTileCacheContours(dd, lcset, orig, cs, ch); }
extern "C" void _1_duDebugDrawTileCachePolyMesh_(duDebugDraw * dd, const struct dtTileCachePolyMesh & lmesh, const float * orig, const float cs, const float ch) { ::duDebugDrawTileCachePolyMesh(dd, lmesh, orig, cs, ch); }
